eraffle/e/urls.py
from django.urls import path

from . import views

app_name = "eraffle"
urlpatterns = [
    path("<spins>/start-raffle", views.index, name="index"),
    path("attendance/", views.attendance, name="attendance"),
    path("winners/", views.winners, name="winners"),
    path("getWinners/", views.getWinners, name="getWinners"),
    path("setSpins/", views.setSpins, name="setSpins"),
    path("backToHomeOrAttendance", views.backToHomeOrAttendance, name="backToHomeOrAttendance")
]

eraffle/eraffle/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("e/", include("e.urls")),
    path('admin/', admin.site.urls),
]

eraffle/e/models.py
from django.db import models

# Create your models here.
class TblCandidates(models.Model):
    candidate_id = models.BigAutoField(db_column='CANDIDATE_ID', primary_key=True)  # Field name made lowercase.
    voter_id = models.BigIntegerField(db_column='VOTER_ID', blank=True, null=True)  # Field name made lowercase.
    position_id = models.BigIntegerField(db_column='POSITION_ID', blank=True, null=True)  # Field name made lowercase.
    remarks = models.TextField(db_column='REMARKS', blank=True, null=True)  # Field name made lowercase.
    class Meta:
        managed = False
        db_table = 'TBL_CANDIDATES'


class TblElectCandidates(models.Model):
    elect_number = models.BigAutoField(db_column='ELECT_NUMBER', primary_key=True)  # Field name made lowercase.
    position_id = models.BigIntegerField(db_column='POSITION_ID', blank=True, null=True)  # Field name made lowercase.
    number_elect = models.IntegerField(db_column='NUMBER_ELECT', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'TBL_ELECT_CANDIDATES'


class TblPosition(models.Model):
    position_id = models.BigAutoField(db_column='POSITION_ID', primary_key=True)  # Field name made lowercase.
    position_description = models.TextField(db_column='POSITION_DESCRIPTION', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'TBL_POSITION'


class TblVoter(models.Model):
    voter_id = models.BigAutoField(db_column='VOTER_ID', primary_key=True)  # Field name made lowercase.
    firstname = models.TextField(db_column='FIRSTNAME', blank=True, null=True)  # Field name made lowercase.
    lastname = models.TextField(db_column='LASTNAME', blank=True, null=True)  # Field name made lowercase.
    status = models.TextField(db_column='STATUS', blank=True, null=True)  # Field name made lowercase.
    area = models.TextField(db_column='AREA', blank=True, null=True)  # Field name made lowercase.
    access_code = models.TextField(db_column='ACCESS_CODE', blank=True, null=True)  # Field name made lowercase.
    image = models.BinaryField(db_column='IMAGE', blank=True, null=True)  # Field name made lowercase.
    registration_status = models.TextField(db_column='REGISTRATION_STATUS', blank=True, null=True)  # Field name made lowercase.
    registration_date = models.TextField(db_column='REGISTRATION_DATE', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'TBL_VOTER'


class TblVotes(models.Model):
    vote_id = models.BigAutoField(db_column='VOTE_ID', primary_key=True)  # Field name made lowercase.
    ballot_number = models.BigIntegerField(db_column='BALLOT_NUMBER', blank=True, null=True)  # Field name made lowercase.
    voter_id = models.BigIntegerField(db_column='VOTER_ID', blank=True, null=True)  # Field name made lowercase.
    candidate_id = models.BigIntegerField(db_column='CANDIDATE_ID', blank=True, null=True)  # Field name made lowercase.
    date_time = models.DateTimeField(db_column='DATE_TIME', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'TBL_VOTES'

class WinnersList(models.Model):
    access_code = models.CharField(max_length=200)
    name = models.CharField(max_length=200)

eraffle/e/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from math import ceil
import random
from .models import TblCandidates,TblElectCandidates,TblPosition,TblVoter,TblVotes, WinnersList

# Create your views here.
def index(request, spins):
    voters = TblVoter.objects.filter(registration_status = 'Registered')
    winners = WinnersList.objects.all()
    if len(winners) != 0:
        new_voters = [i for i in voters if not any(k.access_code == i.access_code for k in winners)]
    else:
        new_voters = voters
    list = []
    masterlist = []
    for a in new_voters:
        dict = {"access_code": a.access_code, "name_code": a.lastname + ", " + a.firstname}
        list.append(dict)
    if(int(spins) <= 0):
        return HttpResponseRedirect(reverse('eraffle:index', args=str(6)))
    counter = ceil(len(list)/int(spins))
    random.shuffle(list)
    sublist = []
    count = 1

    if list != []:
        for index in list:
            sublist.append(index)
            if count == counter:
                masterlist.append(sublist)
                sublist = []
                count = 1
            else:
                count+=1
            if index == list[len(list) - 1] and count < counter and sublist != []:
                masterlist.append(sublist)
        if int(spins) < 6:
            for x in range(6 - int(spins)):
                sublist = []
                masterlist.append(sublist)
        
        if int(spins) > 6:
            return HttpResponseRedirect(reverse('eraffle:index', args=str(6)))
        else:
            return render(request, "app/index.html",{"content1": masterlist[0], "content2": masterlist[1], "content3": masterlist[2], "content4": masterlist[3], "content5": masterlist[4], "content6": masterlist[5]})
    else:
        return render(request, "app/index.html",{"content1": [], "content2": [], "content3": [], "content4": [], "content5": [], "content6": []})
def attendance(request):
    voters = TblVoter.objects.filter(registration_status = 'Registered')
    new_voters_list = []
    for index in voters:
        new_voters_list.append(index.lastname + ", " + index.firstname)
    return render(request, "app/attendance.html", {"attendance": new_voters_list})

def winners(request):
    winners = WinnersList.objects.all()
    return render(request, "app/winners.html", {'winners': winners })

def getWinners(request):
    btn = 'saveWinners' in request.POST
    viewBtn = 'viewWinners' in request.POST
    attendanceBtn = 'checkAttendance' in request.POST
    resetBtn = 'resetList' in request.POST

    if btn == True:
        list = []
        r1 = request.POST['result1']
        r11 = r1.split("_")
        r2 = request.POST['result2']
        r21 = r2.split("_")
        r3 = request.POST['result3']
        r31 = r3.split("_")
        r4 = request.POST['result4']
        r41 = r4.split("_")
        r5 = request.POST['result5']
        r51 = r5.split("_")
        r6 = request.POST['result6']
        r61 = r6.split("_")
        list = [r11, r21, r31, r41, r51, r61]
        for index in list:
            if index != ['']:
                winners = WinnersList(access_code=index[0], name=index[1])
                winners.save()
        winners = WinnersList.objects.all()
        return HttpResponseRedirect(reverse('eraffle:index', args=[6]))
    elif viewBtn == True:
        return HttpResponseRedirect(reverse('eraffle:winners'))
    elif attendanceBtn == True:
        return HttpResponseRedirect(reverse('eraffle:attendance'))
    elif resetBtn == True:
        return HttpResponseRedirect(reverse('eraffle:index', args=[6]))

def setSpins(request):
    spins = request.POST["spins"]
    return HttpResponseRedirect(reverse('eraffle:index', args=[spins]))

def backToHomeOrAttendance(request):
    homeBtn = 'home' in request.POST
    attendanceBtn = 'checkAttendance' in request.POST
    viewBtn = 'viewWinners' in request.POST

    if homeBtn == True:
        return HttpResponseRedirect(reverse('eraffle:index', args=[6]))
    elif attendanceBtn == True:
        return HttpResponseRedirect(reverse('eraffle:attendance'))
    elif viewBtn == True:
        return HttpResponseRedirect(reverse('eraffle:winners'))
    

eraffle/e/templates/app/attendance.html
{% load static %}
<link rel="stylesheet" href="{% static 'style/style.css' %}">

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-raffle</title>
    <link href="{% static 'style/css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body class="mw-100 mh-100">

    <div class="header">
        <p id="tibud">Tibud sa Katibawasan Multi-Purpose Cooperative</p>
        <p id="title">ATTENDANCE LIST</p>
    </div>
    <div class="featureButtons">
        <form action="{% url 'eraffle:backToHomeOrAttendance' %}" method="post">
            {% csrf_token %}
            <input id="viewWinners" type="submit" value="View Winners" name="viewWinners" class="btn btn-primary btn-lg">
            <input id="home" type="submit" value="Home" name="home" class="btn btn-primary btn-lg">
        </form>
    </div>
    <div class="maintable">
        {% for index in attendance %}
            <div class="textDiv">
                {{ index }}
            </div>
        {% endfor %}
    </div>

    <script src="{% static 'script/js/bootstrap.bundle.min.js' %}" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'script/script.js' %}"></script>
</body>
</html>

eraffle/e/templates/app/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'style/style.css' %}">

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-raffle</title>
    <link href="{% static 'style/css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body class="mw-100 mh-100">
    <div class="header">
        <p id="tibud">Tibud sa Katibawasan Multi-Purpose Cooperative</p>
        <p id="title">ATTENDANCE RAFFLE</p>
    </div>
    <div class="featureButtons">
        <form action="{% url 'eraffle:getWinners' %}" method="post">
            {% csrf_token %}
            <input id="checkAttendance" type="submit" value="Check Attendance" name="checkAttendance" class="btn btn-primary btn-lg">
            <input id="viewWinners" type="submit" value="View Winners" name="viewWinners" class="btn btn-primary btn-lg">
            <input id="resetList" type="submit" value="Reset List" name="resetList" class="btn btn-primary btn-lg">
            <input id="saveWinners" type="submit" value="Save Winners" name="saveWinners" class="btn btn-primary btn-lg">
            <button type="button" onclick="openMyModal()" class="btn btn-primary btn-lg">Set Number of Spins</button>
            <input id="result1" type="text" name="result1">
            <input id="result2" type="text" name="result2">
            <input id="result3" type="text" name="result3">
            <input id="result4" type="text" name="result4">
            <input id="result5" type="text" name="result5">
            <input id="result6" type="text" name="result6">
        </form>
    </div>
    <div class="slot">
        <div class="upperSlot">
            <div id ="myContainer1">
                {% for index in content1 %}
                    <div class ="container1">
                        <p id="access_code">{{ index.access_code }}</p>
                        <p id="name_code">{{ index.name_code }}</p>
                    </div>
                {% endfor %}
            </div>
            <div id ="myContainer2">
                {% for index in content2 %}
                    <div class ="container2">
                        <p id="access_code">{{ index.access_code }}</p>
                        <p id="name_code">{{ index.name_code }}</p>
                    </div>
                {% endfor %}
            </div>
            <div id ="myContainer3">
                {% for index in content3 %}
                    <div class ="container3">
                        <p id="access_code">{{ index.access_code }}</p>
                        <p id="name_code">{{ index.name_code }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="lowerSlot">
            <div id ="myContainer4">
                {% for index in content4 %}
                    <div class ="container4">
                        <p id="access_code">{{ index.access_code }}</p>
                        <p id="name_code">{{ index.name_code }}</p>
                    </div>
                {% endfor %}
            </div>
            <div id ="myContainer5">
                {% for index in content5 %}
                    <div class ="container5">
                        <p id="access_code">{{ index.access_code }}</p>
                        <p id="name_code">{{ index.name_code }}</p>
                    </div>
                {% endfor %}
            </div>
            <div id ="myContainer6">
                {% for index in content6 %}
                    <div class ="container6">
                        <p id="access_code">{{ index.access_code }}</p>
                        <p id="name_code">{{ index.name_code }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="spinButtons">
        <div class="containerleft">
            <div class="spintop">
                <button id="spin1" onclick="spin1()">
                    SPIN #1
                </button>
                <button id="spin2" onclick="spin2()">
                    SPIN #2
                </button>
                <button id="spin3" onclick="spin3()">
                    SPIN #3
                </button>
            </div>
            <div class="spinbot">
                <button id="spin4" onclick="spin4()">
                    SPIN #4
                </button>
                <button id="spin5" onclick="spin5()">
                    SPIN #5
                </button>
                <button id="spin6" onclick="spin6()">
                    SPIN #6
                </button>
            </div>
        </div>
        <div class="containerright">
            <button id="spinall" class="btn btn-primary btn-lg" onclick="spinAll()">
                SPIN ALL
            </button>
        </div>
    </div>

    <div id="mySpinModal" class="spinmodal">
        <div class="spin-modal-content">
            <span class="close" onclick="myCloseModal()">&times</span>
            <h3>Number of Spins</h3>
            <form action="{% url 'eraffle:setSpins' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="text" name="spins" id="spins" required><br>
                <button class="btn btn-primary" type="submit" value="generate" name="generate">Set</button><br>
            </form>
        </div>
    </div>

    <div id="mySaveWinnersModal" class="saveWinnersmodal">
        <div class="save-modal-content">
            <span class="close" onclick="myCloseModal2()">&times</span>
            <h3>Save all Winners before spinning</h3>
        </div>
    </div>

    <script src="{% static 'script/js/bootstrap.bundle.min.js' %}" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'script/script.js' %}"></script>
</body>
</html>

eraffle/e/templates/app/winners.html
{% load static %}
<link rel="stylesheet" href="{% static 'style/style.css' %}">

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-raffle</title>
    <link href="{% static 'style/css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body class="mw-100 mh-100">

    <div class="header">
        <p id="tibud">Tibud sa Katibawasan Multi-Purpose Cooperative</p>
        <p id="title">WINNERS LIST</p>
    </div>
    <div class="featureButtons">
        <form action="{% url 'eraffle:backToHomeOrAttendance' %}" method="post">
            {% csrf_token %}
            <input id="checkAttendance" type="submit" value="Check Attendance" name="checkAttendance" class="btn btn-primary btn-lg">
            <input id="home" type="submit" value="Home" name="home" class="btn btn-primary btn-lg">
        </form>
    </div>
    
    <div id="mySpinModal" class="spinmodal">
        <div class="spin-modal-content">
            <span class="close" onclick="myCloseModal()">&times</span>
            <h3>Number of Spins</h3>
            <form action="{% url 'eraffle:setSpins' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="text" name="spins" id="spins" required><br>
                <button class="btn btn-primary" type="submit" value="generate" name="generate">Set</button><br>
            </form>
        </div>
    </div>
    <div class="maintable">
        {% for index in winners %}
            <div class="textDiv">
                {{ index.name }}
            </div>
        {% endfor %}
    </div>

    <div id="mySaveWinnersModal" class="saveWinnersmodal">
        <div class="save-modal-content">
            <span class="close" onclick="myCloseModal2()">&times</span>
            <h3>Save all Winners before spinning</h3>
        </div>
    </div>

    <script src="{% static 'script/js/bootstrap.bundle.min.js' %}" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'script/script.js' %}"></script>
</body>
</html>